# Generated by Django 5.2.11 on 2026-02-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blog_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='interested',
        ),
        migrations.AddField(
            model_name='blog',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
