# Generated by Django 5.2.11 on 2026-02-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_category_options_remove_category_interested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='address',
        ),
    ]
