# Generated by Django 5.2.11 on 2026-02-06 07:34

import blogs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_comment_likes_comment_views_signupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='blogs_category',
            field=models.ForeignKey(default=blogs.models.default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='blogs.category'),
        ),
        migrations.AlterUniqueTogether(
            name='signupmodel',
            unique_together={('blogs_category',)},
        ),
    ]
