# Generated by Django 5.2.11 on 2026-02-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_signupmodel_blogs_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='blogs_category',
            new_name='blog_category',
        ),
        migrations.AlterUniqueTogether(
            name='signupmodel',
            unique_together={('blog_category',)},
        ),
    ]
