# Generated by Django 5.2.11 on 2026-02-06 08:10

import blogs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_rename_blogs_category_signupmodel_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='blog_category',
            field=models.ForeignKey(default=blogs.models.default_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='blogs.category'),
        ),
    ]
