# Generated by Django 5.2.11 on 2026-02-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_alter_signupmodel_blog_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
