# Generated by Django 5.2.11 on 2026-02-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
