# Generated by Django 5.2.11 on 2026-02-06 11:14

import blogs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_remove_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=blogs.models.default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='blogs.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
