# Generated by Django 5.2.11 on 2026-02-07 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_alter_follower_unique_together_follower_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
