# Generated by Django 5.2.11 on 2026-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_following_created_at_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
